### ISSUE TITLE
GFW导致内存异常

### ISSUE THREAD

**Issue by Yancey1989** [k8sp/auto-install#104]
在服务器网络情况不好的情况下（没开VPN）启动 CCTS会导致内存异常
```
liuyijingdeMacBook-Pro:cloud-config-server yanxu$ go run server.go 


panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x17483f]

goroutine 1 [running]:
panic(0x3ec280, 0xc82000a0d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/k8sp/auto-install/cloud-config-server/cache.httpGet(0x527980, 0x77, 0x37e11d600, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/yanxu/go/src/github.com/k8sp/auto-install/cloud-config-server/cache/cache.go:106 +0x4ef
github.com/k8sp/auto-install/cloud-config-server/cache.load(0x527980, 0x77, 0xc820012820, 0x4b, 0x0, 0x0, 0x0)
	/Users/yanxu/go/src/github.com/k8sp/auto-install/cloud-config-server/cache/cache.go:90 +0x66
github.com/k8sp/auto-install/cloud-config-server/cache.New(0x527980, 0x77, 0xc820012820, 0x4b, 0x4b)
	/Users/yanxu/go/src/github.com/k8sp/auto-install/cloud-config-server/cache/cache.go:52 +0x4c
main.makeCacheGetter(0x527980, 0x77, 0x526d80, 0x6d, 0x4ae360, 0x11)
	/Users/yanxu/go/src/github.com/k8sp/auto-install/cloud-config-server/server.go:77 +0x150
main.main()
	/Users/yanxu/go/src/github.com/k8sp/auto-install/cloud-config-server/server.go:40 +0x13d
exit status 2

```

**Comment by wangkuiyi** [comment]
我来看看
